"""
文件说明：
这是 WebSocket 事件常量文件。
组长后续应把所有通知、聊天、已读同步事件名都集中维护在这里，避免前后端不一致。
"""
NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
CHAT_MESSAGE = "CHAT_MESSAGE"
CHAT_READ = "CHAT_READ"
UNREAD_SYNC = "UNREAD_SYNC"
SYSTEM_NOTICE = "SYSTEM_NOTICE"

